import type { AgentPreset } from '@/lib/types/agent';

export const AGENCY_AGENT_PRESETS: AgentPreset[] = [
  {
    id: 'account-manager',
    domain: 'agency',
    name: 'Account Manager',
    description: 'Client communication and relationship management.',
    icon: 'user-check',
    defaultRolePrompt: 'Manage client expectations, status updates, and satisfaction tracking.',
  },
  {
    id: 'brand-strategist',
    domain: 'agency',
    name: 'Brand Strategist',
    description: 'Brand positioning and messaging frameworks.',
    icon: 'sparkles',
    defaultRolePrompt: 'Develop brand voice, positioning statements, and messaging hierarchies.',
  },
  {
    id: 'content-director',
    domain: 'agency',
    name: 'Content Director',
    description: 'Editorial calendar and content strategy.',
    icon: 'pen-tool',
    defaultRolePrompt: 'Plan content calendars, manage editorial flow, and optimize for SEO.',
  },
  {
    id: 'social-media',
    domain: 'agency',
    name: 'Social Media Manager',
    description: 'Multi-platform social strategies.',
    icon: 'share-2',
    defaultRolePrompt: 'Create platform-specific content strategies and engagement plans.',
  },
  {
    id: 'paid-ads',
    domain: 'agency',
    name: 'Paid Ads Specialist',
    description: 'Campaign setup and optimization.',
    icon: 'target',
    defaultRolePrompt: 'Design ad campaigns, A/B tests, and conversion optimization strategies.',
  },
  {
    id: 'seo-specialist',
    domain: 'agency',
    name: 'SEO Specialist',
    description: 'Technical SEO and keyword research.',
    icon: 'search',
    defaultRolePrompt: 'Conduct keyword research, technical audits, and link building strategies.',
  },
  {
    id: 'email-marketer',
    domain: 'agency',
    name: 'Email Marketer',
    description: 'Drip campaigns and automation flows.',
    icon: 'mail',
    defaultRolePrompt: 'Design email sequences, segment audiences, and optimize deliverability.',
  },
  {
    id: 'copywriter',
    domain: 'agency',
    name: 'Copywriter',
    description: 'Sales copy and persuasive messaging.',
    icon: 'file-text',
    defaultRolePrompt: 'Write compelling copy for ads, landing pages, and email campaigns.',
  },
  {
    id: 'analytics-consultant',
    domain: 'agency',
    name: 'Analytics Consultant',
    description: 'Campaign tracking and reporting.',
    icon: 'bar-chart-3',
    defaultRolePrompt: 'Set up tracking, analyze campaign performance, and create client reports.',
  },
  {
    id: 'project-coordinator',
    domain: 'agency',
    name: 'Project Coordinator',
    description: 'Timeline management and deliverables.',
    icon: 'calendar',
    defaultRolePrompt: 'Manage project timelines, coordinate deliverables, and track milestones.',
  },
];
