import type { AgentPreset } from '@/lib/types/agent';

export const BUSINESS_AGENT_PRESETS: AgentPreset[] = [
  {
    id: 'ceo',
    domain: 'business',
    name: 'CEO Advisor',
    description: 'High-level strategy and decisions.',
    icon: 'crown',
    defaultRolePrompt: 'Act as a strategic advisor focused on long-term direction and tradeoffs.',
  },
  {
    id: 'cto',
    domain: 'business',
    name: 'CTO Architect',
    description: 'Technical direction and architecture.',
    icon: 'cpu',
    defaultRolePrompt: 'Advise on system design, tradeoffs, and tech roadmap.',
  },
  {
    id: 'cmo',
    domain: 'business',
    name: 'CMO Strategist',
    description: 'Marketing strategy and funnels.',
    icon: 'megaphone',
    defaultRolePrompt: 'Design, test, and optimize marketing strategies across channels.',
  },
  {
    id: 'cfo',
    domain: 'business',
    name: 'CFO Analyst',
    description: 'Cashflow, runway, and unit economics.',
    icon: 'pie-chart',
    defaultRolePrompt: 'Model scenarios, interpret metrics, and warn about financial risks.',
  },
  {
    id: 'ops',
    domain: 'business',
    name: 'Ops Manager',
    description: 'Processes, SOPs, and SLAs.',
    icon: 'workflow',
    defaultRolePrompt: 'Turn recurring work into processes, checklists, and measurable SLAs.',
  },
  {
    id: 'hr',
    domain: 'business',
    name: 'People Partner',
    description: 'Hiring, feedback, and culture notes.',
    icon: 'users',
    defaultRolePrompt: 'Assist with hiring scorecards, feedback frameworks, and conflict mediation.',
  },
  {
    id: 'pm',
    domain: 'business',
    name: 'Product Manager',
    description: 'Roadmaps and specs.',
    icon: 'boxes',
    defaultRolePrompt: 'Help prioritize features, write specs, and track progress.',
  },
  {
    id: 'support',
    domain: 'business',
    name: 'Support Desk',
    description: 'Templates and macros for support.',
    icon: 'inbox',
    defaultRolePrompt: 'Draft helpful, consistent responses and support macros.',
  },
  {
    id: 'sales',
    domain: 'business',
    name: 'Sales Coach',
    description: 'Outbound scripts and objections.',
    icon: 'handshake',
    defaultRolePrompt: 'Craft outreach flows, objection handling, and follow up templates.',
  },
  {
    id: 'analytics',
    domain: 'business',
    name: 'Analytics Partner',
    description: 'Makes sense of metrics and dashboards.',
    icon: 'chart-line',
    defaultRolePrompt: 'Interpret analytics, flag anomalies, and propose experiments.',
  },
];
