import type { AgentPreset } from '@/lib/types/agent';

export const DEVELOPER_AGENT_PRESETS: AgentPreset[] = [
  {
    id: 'architect',
    domain: 'developer',
    name: 'System Architect',
    description: 'Architecture design and technical decisions.',
    icon: 'git-branch',
    defaultRolePrompt: 'Design system architecture, evaluate tradeoffs, and document decisions.',
  },
  {
    id: 'code-reviewer',
    domain: 'developer',
    name: 'Code Reviewer',
    description: 'Code quality and best practices.',
    icon: 'file-code',
    defaultRolePrompt: 'Review code for quality, security, performance, and maintainability.',
  },
  {
    id: 'devops',
    domain: 'developer',
    name: 'DevOps Engineer',
    description: 'CI/CD, infrastructure, and deployments.',
    icon: 'server',
    defaultRolePrompt: 'Manage infrastructure, automate deployments, and ensure reliability.',
  },
  {
    id: 'security',
    domain: 'developer',
    name: 'Security Analyst',
    description: 'Vulnerability scanning and secure coding.',
    icon: 'shield',
    defaultRolePrompt: 'Identify security vulnerabilities and recommend mitigation strategies.',
  },
  {
    id: 'qa-engineer',
    domain: 'developer',
    name: 'QA Engineer',
    description: 'Test strategies and automation.',
    icon: 'check-circle',
    defaultRolePrompt: 'Design test plans, write test cases, and automate testing workflows.',
  },
  {
    id: 'api-designer',
    domain: 'developer',
    name: 'API Designer',
    description: 'REST/GraphQL API design.',
    icon: 'plug',
    defaultRolePrompt: 'Design clean, scalable APIs with proper versioning and documentation.',
  },
  {
    id: 'database-admin',
    domain: 'developer',
    name: 'Database Admin',
    description: 'Schema design and query optimization.',
    icon: 'database',
    defaultRolePrompt: 'Design database schemas, optimize queries, and manage migrations.',
  },
  {
    id: 'performance',
    domain: 'developer',
    name: 'Performance Engineer',
    description: 'Profiling and optimization.',
    icon: 'zap',
    defaultRolePrompt: 'Profile applications, identify bottlenecks, and optimize performance.',
  },
  {
    id: 'documentation',
    domain: 'developer',
    name: 'Tech Writer',
    description: 'API docs and technical guides.',
    icon: 'book',
    defaultRolePrompt: 'Write clear technical documentation, API references, and tutorials.',
  },
  {
    id: 'automation',
    domain: 'developer',
    name: 'Automation Specialist',
    description: 'Scripting and workflow automation.',
    icon: 'repeat',
    defaultRolePrompt: 'Automate repetitive tasks, build scripts, and integrate systems.',
  },
];
